# This file was generated by GoReleaser. DO NOT EDIT.
cask "post" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "e98a2f0d21b95c6dd7016f3e72644bffe3a01cccae73c9cf54a5ea063c0bde73"
      url "https://github.com/buildaloudhq/post/releases/download/v#{version}/post_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8280c4ca837ed9b12e7dd9341ffbc90c6196cb8d75d1466a0b3be60d9afa8025"
      url "https://github.com/buildaloudhq/post/releases/download/v#{version}/post_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "29420476d5ccc9b92e1d6745d96370f4641c32f16d39a66e0413aff0153175db"
      url "https://github.com/buildaloudhq/post/releases/download/v#{version}/post_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "251ebd18c4cd62e8809e3196c5b19fd1bcf3ad5251874b355f47599aa5575f47"
      url "https://github.com/buildaloudhq/post/releases/download/v#{version}/post_#{version}_linux_arm64.tar.gz"
    end
  end

  name "post"
  desc "Draft and cross-post to social-media platforms"
  homepage "https://buildaloud.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "post"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/post"]
    end
  end

  # No zap stanza required

end
