# This file was generated by GoReleaser. DO NOT EDIT.
cask "post" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "e75744748dc6173983deef0fa470e25733d0333412527250a9bd4d069890a1c1"
      url "https://github.com/buildaloudhq/post/releases/download/v#{version}/post_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b0183673890b1ea608658af990e067bf633d6c780d52b641bb1d09a683d6eb83"
      url "https://github.com/buildaloudhq/post/releases/download/v#{version}/post_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8b93434dc3ec4e499d7ecec37d6dec1450523a2903ea2f8aedd270f19d541962"
      url "https://github.com/buildaloudhq/post/releases/download/v#{version}/post_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "37b272754d3ab9eb983de62d9b09871c55c31a923cd468f0b4b2fb1deb7299fb"
      url "https://github.com/buildaloudhq/post/releases/download/v#{version}/post_#{version}_linux_arm64.tar.gz"
    end
  end

  name "post"
  desc "Draft and cross-post to social-media platforms"
  homepage "https://buildaloud.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "post"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/post"]
    end
  end

  # No zap stanza required

end
