# This file was generated by GoReleaser. DO NOT EDIT.
cask "post" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "5e28d5959905b72a13c2751c28534d78b2486e60d9145fca68d558e93c8915db"
      url "https://github.com/buildaloudhq/post/releases/download/v#{version}/post_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a954d1c0ced9d5f1c45df308284652d91144db4e75feb9dad4960a12ab601644"
      url "https://github.com/buildaloudhq/post/releases/download/v#{version}/post_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "b0083eade580c294fd69b8e554aa8cd7bb3e972f7cb7629e70d8842a886cd737"
      url "https://github.com/buildaloudhq/post/releases/download/v#{version}/post_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a32b2c7f60d478ce6d6304e175eeb531c1be77d008d77040747667ca85115220"
      url "https://github.com/buildaloudhq/post/releases/download/v#{version}/post_#{version}_linux_arm64.tar.gz"
    end
  end

  name "post"
  desc "Draft and cross-post to social-media platforms"
  homepage "https://buildaloud.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "post"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/post"]
    end
  end

  # No zap stanza required

end
